services:
  nginx:
    image: civitas-proxy:${PROXY_VERSION}
    container_name: gateway
    ports:
      - "9091:9090"
      - "9444:9443"
    env_file:
      - ./conf/nginx/env/dev.env
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./certs:/etc/nginx/ssl:ro
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - civitas-api
    networks:
      - civitas

  civitas-api:
    image: civitas-api
    container_name: api
    build:
      context: .
      dockerfile: Civitas.Api/Dockerfile
    ports:
      - "7080:7080"
      - "7081:7081"
    environment:
      - ASPNETCORE_URLS=${ASPNETCORE_URLS}
      - Kestrel__Certificates__Default__Password=${Kestrel__Certificates__Default__Password}
      - Kestrel__Certificates__Default__Path=${Kestrel__Certificates__Default__Path}
      - ASPNETCORE_ENVIRONMENT=${ASPNETCORE_ENVIRONMENT}
      - API_KEY=${API_KEY}
      - Redis__ConnectionString=civitas-cache:6379
    networks:
      - civitas

  redis:
    image: redis/redis-stack:latest
    container_name: civitas-cache
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    networks:
      - civitas

volumes:
  redis-data:

networks:
  civitas:
    driver: bridge
