services:
  nginx:
    image: civitas-proxy:${PROXY_VERSION}
    container_name: gateway
    ports:
      - "9091:9091"
      - "9443:9443"
    env_file:
      - ./conf/nginx/env/dev.env
    volumes:
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf:ro # Nginx configuration
      - ./conf/nginx/default.conf.template:/etc/nginx/templates/default.conf.template
      - ./certs:/etc/nginx/ssl:ro # Mount certificates for SSL
      - ./logs/nginx:/var/log/nginx
    depends_on:
      - civitas-api

  civitas-api:
    image: civitas-api
    container_name: api
    build:
      context: .
      dockerfile: Civitas.Api/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  redis:
    image: redis/redis-stack:latest
    container_name: civitas-cache
    ports:
      - "6379:6379"
      - "8001:8001" # Redis Stack web UI
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  redis-data:

networks:
  default:
    driver: bridge
