services:
  nginx:
    image: nginx:latest
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - civitas-api


  civitas-api:
    image: civitas-api
    build:
      context: .
      dockerfile: Civitas.Api/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development


networks:
  default:
    driver: bridge